// Generated by scripts/build_catalog_artwork.py.
(() => {
  "use strict";
  const BOARDS = Object.freeze({"maharashtra-board":{"src":"/catalog-artwork/boards/logos/maharashtra-board.png","alt":"Maharashtra State Board official logo"},"cbse":{"src":"/catalog-artwork/boards/logos/cbse.png","alt":"CBSE official logo"},"cisce":{"src":"/catalog-artwork/boards/logos/cisce.webp","alt":"CISCE — ICSE & ISC official logo"},"tamil-nadu-board":{"src":"/catalog-artwork/boards/logos/tamil-nadu-board.png","alt":"Tamil Nadu State Board official logo"}});
  const parts = () => location.pathname.split("/").filter(Boolean);
  const coverPath = (board, grade, slug) => {
    const path = `/catalog-artwork/books/covers/${board}/${grade}/${slug}.webp`;
    return board === "maharashtra-board" ? `${path}?v=20260817-official` : path;
  };
  const coverAlt = (value) => `${String(value || "Textbook")
    .replace(/\btextbook solutions\b|\bsolutions\b/gi, "")
    .trim()} textbook cover`;

  function setPicture(picture, src, alt, eager) {
    if (!picture || !src) return;
    let image = picture.querySelector("img");
    const sources = picture.querySelectorAll("source");
    if (!image || picture.children.length !== 1 || sources.length) {
      image = document.createElement("img");
      picture.replaceChildren(image);
    }
    image.alt = alt || image.alt || "Textbook cover";
    image.className = "catalog-real-book-cover";
    image.decoding = "async";
    image.fetchPriority = eager ? "high" : "low";
    image.height = 300;
    image.loading = eager ? "eager" : "lazy";
    if (image.getAttribute("src") !== src) image.src = src;
    image.removeAttribute("srcset");
    image.width = 216;
  }

  function setLogo(image, artwork, size, eager = false) {
    if (!image || !artwork) return;
    const src = artwork.src.replace(/\.(?:png|webp)$/i, "-384.webp");
    image.alt = artwork.alt;
    image.className = "board-official-logo";
    image.decoding = "async";
    image.fetchPriority = eager ? "high" : "low";
    image.loading = eager ? "eager" : "lazy";
    if (image.getAttribute("src") !== src) image.src = src;
    image.removeAttribute("srcset");
    image.width = size;
    image.height = size;
  }

  function applyArtwork() {
    const route = parts();
    const [board, grade, subject, book] = route;
    const pageConfig = window.__STUDYWUDY_ARTWORK_PAGE__ || {};
    const allowed = pageConfig.pathname === location.pathname && Array.isArray(pageConfig.allowedSlugs)
      ? new Set(pageConfig.allowedSlugs)
      : null;

    document.querySelectorAll(".book-card[data-book-slug]").forEach((card, index) => {
      const slug = card.getAttribute("data-book-slug");
      if (allowed && !allowed.has(slug)) {
        card.remove();
        return;
      }
      setPicture(
        card.querySelector(".catalog-artwork-picture"),
        coverPath(board, grade, slug),
        coverAlt(card.querySelector("h2, h3")?.textContent),
        index === 0,
      );
    });

    if (route.length === 4) {
      setPicture(
        document.querySelector(".book-hero .catalog-artwork-picture"),
        coverPath(board, grade, book),
        coverAlt(document.querySelector(".book-hero h1")?.textContent),
        true,
      );
    }

    for (const [slug, artwork] of Object.entries(BOARDS)) {
      setLogo(document.querySelector(`.board-card-${slug} .board-artwork img`), artwork, 192);
    }
    if (route.length === 1 && BOARDS[board]) {
      setLogo(document.querySelector(".catalog-stat-artwork img"), BOARDS[board], 180, true);
    }
    if (location.pathname.replace(/\/+$/, "") === "/boards") {
      document.querySelectorAll(".board-explorer-compact").forEach((element) => element.remove());
    }
    if (allowed) {
      const count = allowed.size;
      const label = String(pageConfig.streamLabel || "Selected");
      const summary = document.querySelector(".catalog-section .section-mini-heading > p");
      if (summary) summary.textContent = `${count} ${count === 1 ? "textbook" : "textbooks"} for ${label}`;
      const heading = document.querySelector(".subject-hero h1");
      if (heading && !heading.parentElement?.querySelector(".stream-context")) {
        const context = document.createElement("span");
        context.className = "stream-context";
        context.textContent = `${label} stream`;
        heading.after(context);
      }
    }
  }

  let scheduled = false;
  function scheduleArtwork() {
    if (scheduled) return;
    scheduled = true;
    queueMicrotask(() => {
      scheduled = false;
      applyArtwork();
    });
  }

  function startAfterHydration(attempt = 0) {
    if (!document.querySelector("next-route-announcer") && attempt < 300) {
      requestAnimationFrame(() => startAfterHydration(attempt + 1));
      return;
    }
    new MutationObserver(scheduleArtwork).observe(document.documentElement, {
      childList: true,
      subtree: true,
    });
    addEventListener("popstate", scheduleArtwork);
    applyArtwork();
  }

  startAfterHydration();
})();
