// Generated by scripts/build_catalog_artwork.py.
(() => {
  "use strict";
  if (window.__STUDYWUDY_ARTWORK_RUNTIME_ACTIVE__) return;
  window.__STUDYWUDY_ARTWORK_RUNTIME_ACTIVE__ = true;
  const BOARDS = Object.freeze({"maharashtra-board":{"src":"/catalog-artwork/boards/logos/maharashtra-board.png","alt":"Maharashtra State Board official logo"},"cbse":{"src":"/catalog-artwork/boards/logos/cbse.png","alt":"CBSE official logo"},"cisce":{"src":"/catalog-artwork/boards/logos/cisce.webp","alt":"CISCE — ICSE & ISC official logo"},"tamil-nadu-board":{"src":"/catalog-artwork/boards/logos/tamil-nadu-board.png","alt":"Tamil Nadu State Board official logo"}});
  const ARTWORK_SELECTOR = ".book-card[data-book-slug], .book-hero, .board-artwork, .catalog-stat-artwork, .catalog-subject-book-covers, [class*='SubjectGrid-module'][class*='__card']";
  const ARTWORK_CONTAINER_SELECTOR = ".catalog-artwork-picture, .board-artwork, .catalog-stat-artwork, .catalog-subject-book-covers, .section-mini-heading, .subject-hero";
  const parts = () => location.pathname.split("/").filter(Boolean);
  const coverPath = (board, grade, slug) => {
    const path = `/catalog-artwork/books/covers/${board}/${grade}/${slug}.webp`;
    return board === "maharashtra-board" ? `${path}?v=20260817-official` : path;
  };
  const coverAlt = (value) => `${String(value || "Textbook")
    .replace(/\btextbook solutions\b|\bsolutions\b/gi, "")
    .trim()} textbook cover`;

  function setPicture(picture, src, alt, eager) {
    if (!picture || !src) return;
    let image = picture.querySelector("img");
    picture.querySelectorAll("source").forEach((source) => {
      if (source.getAttribute("srcset") !== src) source.setAttribute("srcset", src);
      source.removeAttribute("sizes");
      source.setAttribute("type", "image/webp");
    });
    if (!image) {
      image = document.createElement("img");
      picture.append(image);
    }
    image.alt = alt || image.alt || "Textbook cover";
    image.className = "catalog-real-book-cover";
    image.decoding = "async";
    image.fetchPriority = eager ? "high" : "low";
    image.height = 300;
    image.loading = eager ? "eager" : "lazy";
    if (image.getAttribute("src") !== src) image.src = src;
    image.removeAttribute("srcset");
    image.width = 216;
  }

  function setLogo(image, artwork, size, eager = false) {
    if (!image || !artwork) return;
    const src = artwork.src.replace(/\.(?:png|webp)$/i, "-384.webp");
    image.alt = artwork.alt;
    image.className = "board-official-logo";
    image.decoding = "async";
    image.fetchPriority = eager ? "high" : "low";
    image.loading = eager ? "eager" : "lazy";
    if (image.getAttribute("src") !== src) image.src = src;
    image.removeAttribute("srcset");
    image.width = size;
    image.height = size;
  }

  function setSubjectCoverSet(card, covers) {
    if (!card || !Array.isArray(covers) || !covers.length) return;
    const sources = covers.map((cover) => String(cover.src || "")).filter(Boolean);
    if (!sources.length) return;
    const signature = sources.join("|");
    let coverSet = card.querySelector(":scope > .catalog-subject-book-covers");
    if (coverSet?.dataset.coverSignature === signature) return;
    if (!coverSet) {
      coverSet = document.createElement("span");
      card.prepend(coverSet);
    }
    const layout = sources.length === 1 ? "single" : sources.length <= 4 ? "fan" : "grid";
    coverSet.className = `catalog-subject-book-covers catalog-subject-book-covers-${layout}`;
    coverSet.dataset.coverCount = String(sources.length);
    coverSet.dataset.coverSignature = signature;
    coverSet.setAttribute("aria-hidden", "true");
    coverSet.style.setProperty("--cover-cols", String(layout === "grid" ? Math.ceil(sources.length / 2) : sources.length));
    coverSet.replaceChildren(...sources.map((src) => {
      const image = document.createElement("img");
      image.alt = "";
      image.setAttribute("aria-hidden", "true");
      image.decoding = "async";
      image.height = 96;
      image.loading = "lazy";
      image.src = src;
      image.width = 68;
      return image;
    }));
  }

  function applyArtwork() {
    const route = parts();
    const [board, grade, subject, book] = route;
    const pageConfig = window.__STUDYWUDY_ARTWORK_PAGE__ || {};
    const allowed = pageConfig.pathname === location.pathname && Array.isArray(pageConfig.allowedSlugs)
      ? new Set(pageConfig.allowedSlugs)
      : null;

    if (route.length === 2 && pageConfig.pathname === location.pathname && pageConfig.subjectCovers) {
      for (const [subjectSlug, covers] of Object.entries(pageConfig.subjectCovers)) {
        const href = `/${board}/${grade}/${subjectSlug}`;
        setSubjectCoverSet(document.querySelector(`a[class*="SubjectGrid-module"][class*="__card"][href="${CSS.escape(href)}"]`), covers);
      }
    }

    document.querySelectorAll(".book-card[data-book-slug]").forEach((card, index) => {
      const slug = card.getAttribute("data-book-slug");
      if (allowed && !allowed.has(slug)) {
        card.remove();
        return;
      }
      setPicture(
        card.querySelector(".catalog-artwork-picture"),
        coverPath(board, grade, slug),
        coverAlt(card.querySelector("h2, h3")?.textContent),
        index === 0,
      );
    });

    if (route.length === 4) {
      setPicture(
        document.querySelector(".book-hero .catalog-artwork-picture"),
        coverPath(board, grade, book),
        coverAlt(document.querySelector(".book-hero h1")?.textContent),
        true,
      );
    }

    for (const [slug, artwork] of Object.entries(BOARDS)) {
      setLogo(document.querySelector(`.board-card-${slug} .board-artwork img`), artwork, 192);
    }
    if (route.length === 1 && BOARDS[board]) {
      setLogo(document.querySelector(".catalog-stat-artwork img"), BOARDS[board], 180, true);
    }
    if (location.pathname.replace(/\/+$/, "") === "/boards") {
      document.querySelectorAll(".board-explorer-compact").forEach((element) => element.remove());
    }
    if (allowed) {
      const count = allowed.size;
      const label = String(pageConfig.streamLabel || "Selected");
      const summary = document.querySelector(".catalog-section .section-mini-heading > p");
      const summaryText = `${count} ${count === 1 ? "textbook" : "textbooks"} for ${label}`;
      if (summary && summary.textContent !== summaryText) summary.textContent = summaryText;
      const heading = document.querySelector(".subject-hero h1");
      if (heading && !heading.parentElement?.querySelector(".stream-context")) {
        const context = document.createElement("span");
        context.className = "stream-context";
        context.textContent = `${label} stream`;
        heading.after(context);
      }
    }
  }

  let scheduled = false;
  function scheduleArtwork() {
    if (scheduled) return;
    scheduled = true;
    queueMicrotask(() => {
      scheduled = false;
      applyArtwork();
    });
  }

  function mutationAffectsArtwork(records) {
    return records.some((record) => {
      const target = record.target instanceof Element ? record.target : record.target.parentElement;
      if (target?.closest(ARTWORK_CONTAINER_SELECTOR)) return true;
      return [...record.addedNodes].some((node) => node instanceof Element
        && (node.matches(ARTWORK_SELECTOR) || node.querySelector(ARTWORK_SELECTOR)));
    });
  }

  function startArtworkRuntime() {
    const observer = new MutationObserver((records) => {
      if (mutationAffectsArtwork(records)) scheduleArtwork();
    });
    observer.observe(document.body || document.documentElement, {
      childList: true,
      subtree: true,
    });
    addEventListener("popstate", scheduleArtwork);
    addEventListener("pageshow", scheduleArtwork);
    applyArtwork();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", startArtworkRuntime, { once: true });
  } else {
    startArtworkRuntime();
  }
})();
